version: "3.1"

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "6000:5432"
    labels:
      com.swc.kind: "db"
